version: '3'
services:
  app_pdfkit:
    build:
      context: .
      dockerfile: Dockerfile_pdfkit
    volumes:
      - ./:/app
  app_thinreports:
    build: .
    volumes:
    - ./:/app
    - bundle_path:/bundle
    environment:
      BUNDLE_PATH: /bundle
volumes:
  bundle_path:
